name: benchmarkhor
description: >
  Benchmark comparison tool. Provides ways to compare
  benchmark results as a whole, as opposed to just
  a few summary numbers.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
   lzma: ^1.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
