name: benchmarkhor
description: >
  Benchmark comparison tool. Provides ways to compare
  benchmark results as a whole, as opposed to just
  a few summary numbers.
version: 0.1.0
repository: https://github.com/filiph/benchmarkhor

executables:
  benchextract:
  benchcompare:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  logging: ^1.0.1
  lzma: ^1.0.1
  path: ^1.8.0
  t_stats: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
