import 'dart:convert';
import 'dart:io';

import 'package:adb_server/api.dart';
import 'package:adb_server/config.dart';
import 'package:adb_server/llms_txt.dart';
import 'package:adb_server/main.server.options.dart';
import 'package:adb_server/models.dart';
import 'package:adb_server/runner.dart';
import 'package:adb_server/session_store.dart';
import 'package:jaspr/server.dart' hide Request, Response;
import 'package:path/path.dart' as p;
import 'package:shelf/shelf.dart';
import 'package:test/test.dart';

void main() {
  /// Keys that `includeIfNull: false` omits from a default toJson() but that
  /// must still be documented.
  const sessionNullableKeys = {'trial_timeout_seconds', 'launch_activity'};
  const variantNullableKeys = {'source', 'test_apk'};

  test('SessionSpec field descriptions cover toJson keys both ways', () {
    const sample = SessionSpec(
      name: 'example',
      variants: {'baseline': VariantSpec()},
      package: 'com.example.app',
      testPackage: 'com.example.app.test',
      deviceResultDir: '/sdcard/Android/data/com.example.app/files',
    );
    final jsonKeys = sample.toJson().keys.toSet();
    final documented = kSessionSpecFieldDescriptions.keys.toSet();

    final missingDocs = jsonKeys.difference(documented);
    final orphanDocs = documented
        .difference(jsonKeys)
        .difference(sessionNullableKeys);

    expect(
      missingDocs,
      isEmpty,
      reason:
          'SessionSpec.toJson() keys lack descriptions in '
          'kSessionSpecFieldDescriptions: $missingDocs',
    );
    expect(
      orphanDocs,
      isEmpty,
      reason:
          'kSessionSpecFieldDescriptions has keys not in '
          'SessionSpec.toJson() (and not known-nullable): $orphanDocs',
    );
    // Nullable keys must be documented even though absent from toJson().
    for (final key in sessionNullableKeys) {
      expect(
        documented,
        contains(key),
        reason: 'nullable SessionSpec field "$key" must have a description',
      );
    }
  });

  test('VariantSpec field descriptions cover toJson keys both ways', () {
    final jsonKeys = const VariantSpec().toJson().keys.toSet();
    final documented = kVariantSpecFieldDescriptions.keys.toSet();

    final missingDocs = jsonKeys.difference(documented);
    final orphanDocs = documented
        .difference(jsonKeys)
        .difference(variantNullableKeys);

    expect(
      missingDocs,
      isEmpty,
      reason:
          'VariantSpec.toJson() keys lack descriptions in '
          'kVariantSpecFieldDescriptions: $missingDocs',
    );
    expect(
      orphanDocs,
      isEmpty,
      reason:
          'kVariantSpecFieldDescriptions has keys not in '
          'VariantSpec.toJson() (and not known-nullable): $orphanDocs',
    );
    for (final key in variantNullableKeys) {
      expect(
        documented,
        contains(key),
        reason: 'nullable VariantSpec field "$key" must have a description',
      );
    }
  });

  test('VariantSpec.source is optional and additive', () {
    final without = VariantSpec.fromJson({
      'apk': 'a.apk',
      'test_apk': 'a-test.apk',
    });
    expect(without.source, isNull);
    expect(without.toJson().containsKey('source'), isFalse);

    final withSource = VariantSpec.fromJson({
      'apk': 'a.apk',
      'test_apk': 'a-test.apk',
      'source': 'git 4f2a1c9 (dirty)',
    });
    expect(withSource.source, 'git 4f2a1c9 (dirty)');
    expect(withSource.toJson()['source'], 'git 4f2a1c9 (dirty)');
  });

  test('generateLlmsTxt is non-empty and contains load-bearing literals', () {
    final doc = generateLlmsTxt(
      gitCommit: 'testcommit',
      generatedAt: DateTime.utc(2026, 8, 26, 12),
    );
    expect(doc, isNotEmpty);
    expect(doc, contains('BENCH_DONE'));
    expect(doc, contains('DONE'));
    expect(doc, contains('assembleProfileAndroidTest'));
    expect(doc, contains('session.json'));
    expect(doc, contains('generated by adb_server testcommit'));
  });

  test('the worked session.json example parses as a valid SessionSpec', () {
    // The example is advertised as "complete, valid". Prove it against the same
    // entry point the server uses, so the document cannot start handing agents
    // a spec that would land in state `invalid`.
    final doc = generateLlmsTxt(gitCommit: 'testcommit');
    final start = doc.indexOf('### A complete, valid session.json');
    expect(start, greaterThan(-1), reason: 'the worked example section is gone');

    final braceStart = doc.indexOf('{', start);
    final braceEnd = doc.lastIndexOf('}', doc.indexOf('\n## ', start));
    final snippet = doc.substring(braceStart, braceEnd + 1);

    final spec = SessionSpec.fromJson(
      jsonDecode(snippet) as Map<String, dynamic>,
    );
    expect(spec.variants, hasLength(2));
    expect(spec.variants['baseline']!.apk, 'baseline.apk');
    expect(spec.variants['improved']!.source, isNotNull);
    expect(spec.expectedResultFiles, contains('frames.jsonl'));
  });

  test('the worked pure Dart session.json example parses as a valid SessionSpec', () {
    final doc = generateLlmsTxt(gitCommit: 'testcommit');
    final start = doc.indexOf('## Example session.json for Pathway B (Pure Dart Single APK)');
    expect(start, greaterThan(-1), reason: 'the pure dart worked example section is gone');

    final braceStart = doc.indexOf('{', start);
    final braceEnd = doc.lastIndexOf('}', doc.indexOf('\n## ', start + 10));
    final snippet = doc.substring(braceStart, braceEnd + 1);

    final spec = SessionSpec.fromJson(
      jsonDecode(snippet) as Map<String, dynamic>,
    );
    expect(spec.variants, hasLength(2));
    expect(spec.variants['baseline']!.apk, 'baseline.apk');
    expect(spec.variants['baseline']!.testApk, isNull);
    expect(spec.launchActivity, isNotNull);
    expect(spec.expectedResultFiles, contains('iterations.jsonl'));
  });

  test('no Dart toString() forms leak into the document', () {
    // `SessionSpec.toJson()` leaves nested freezed objects unconverted, so a
    // naive `toString()` prints camelCase field names that do not exist in
    // session.json — directly contradicting the snake_case table beside them.
    final doc = generateLlmsTxt(gitCommit: 'testcommit');
    expect(doc, isNot(contains('VariantSpec(')));
    expect(doc, isNot(contains('testApk')));
    expect(doc, isNot(contains('(MISSING DESCRIPTION)')));
  });

  group('GET /llms.txt', () {
    late Directory tempDir;
    late Handler handler;

    setUp(() {
      Jaspr.initializeApp(options: defaultServerOptions);
      tempDir = Directory.systemTemp.createTempSync('adb_llms_txt_test_');
      final store = SessionStore(tempDir.path);
      final config = Config(
        dutAddress: '127.0.0.1:5555',
        dataDir: tempDir.path,
        port: 8080,
        adbPath: 'adb',
        pollIntervalSeconds: 15,
        defaultTrialTimeoutSeconds: 1800,
        thermalGateCelsius: null,
        thermalGateTimeoutSeconds: 300,
        deviceProfileFile: null,
        deviceResetFile: null,
        profilesDir: p.join(tempDir.path, 'profiles'),
        precompilePackage: true,
        logLevel: 'info',
        gitCommit: 'abdabdabd',
      );
      final runner = Runner(config: config, sessionStore: store);
      final api = Api(config: config, sessionStore: store, runner: runner);
      handler = api.handler;
    });

    tearDown(() {
      tempDir.deleteSync(recursive: true);
    });

    test('serves text/plain with load-bearing content, no adb', () async {
      final request = Request('GET', Uri.parse('http://localhost/llms.txt'));
      final response = await handler(request);
      expect(response.statusCode, 200);
      expect(response.headers['content-type'], contains('text/plain'));

      final body = await response.readAsString();
      expect(body, isNotEmpty);
      expect(body, contains('BENCH_DONE'));
      expect(body, contains('DONE'));
      expect(body, contains('assembleProfileAndroidTest'));
      expect(body, contains('session.json'));
      // Generating the document must not touch adb; config still has a real
      // adbPath string but the handler never invokes it.
      expect(body, contains('generated by adb_server abdabdabd'));
    });
  });
}
