name: Continuous testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies (root)
        run: flutter pub get

      - name: Install dependencies (adb_server)
        working-directory: adb_server
        run: flutter pub get

      - name: Install dependencies (example_apk)
        working-directory: example_apk
        run: flutter pub get

      - name: Build fake_adb
        working-directory: adb_server/test/fixtures/fake_adb
        run: dart compile exe fake_adb.dart -o adb

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Analyze example_apk
        working-directory: example_apk
        run: flutter analyze --fatal-infos

      - name: Run tests (root)
        run: flutter test

      - name: Run tests (adb_server)
        working-directory: adb_server
        run: flutter test

      - name: Run tests (example_apk)
        working-directory: example_apk
        run: flutter test
